-- Create a private table for todos
create table if not exists todos (
  id bigint generated by default as identity primary key,
  user_id text not null default (auth.jwt() ->> 'sub'),
  task text check (char_length(task) > 3),
  is_complete boolean default false,
  inserted_at timestamptz default timezone('utc', now()) not null
);

alter table todos enable row level security;

-- Policy to allow users to select their own todos
-- We use (auth.jwt() ->> 'sub') to get the Clerk User ID
create policy "Users can select their own todos"
  on todos for select
  using ( (select auth.jwt() ->> 'sub') = user_id );

-- Policy to allow users to insert their own todos
create policy "Users can insert their own todos"
  on todos for insert
  with check ( (select auth.jwt() ->> 'sub') = user_id );

-- Policy to allow users to update their own todos
create policy "Users can update their own todos"
  on todos for update
  using ( (select auth.jwt() ->> 'sub') = user_id );

-- Policy to allow users to delete their own todos
create policy "Users can delete their own todos"
  on todos for delete
  using ( (select auth.jwt() ->> 'sub') = user_id );
